(function(){function d(){}function a(b){this.callbackUrl=b;this.viewed=!1;this.timer=null;this.initChecker()}d.prototype.isChromium=function(){var b=-1<navigator.userAgent.toLowerCase().indexOf("edge"),c=-1<navigator.userAgent.indexOf("Chrome"),e=-1<navigator.userAgent.toLowerCase().indexOf("op");return!b&&(c||e)};d.prototype.isIE=function(){return"Microsoft Internet Explorer"===navigator.appName&&-1<navigator.userAgent.indexOf("MSIE")||"Netscape"===navigator.appName&&-1<navigator.userAgent.indexOf("Trident")};
d.prototype.isSafari=function(){return-1<navigator.userAgent.indexOf("Safari")&&-1<navigator.vendor.indexOf("Apple")};d.prototype.createCallbackPixel=function(b){var c=document.createElement("img");c.src=b;c.style.cssText="height: 1px; width: 1px; display: none;";document.body.appendChild(c)};d.prototype.getPointCoordinatesByPercent=function(b,c){return{x:window.innerWidth*(parseFloat(b)/100),y:window.innerHeight*(parseFloat(c)/100)}};d.prototype.getGridPoints=function(b,c){for(var e=[],a=window.innerWidth-
1,f=window.innerHeight-1,g=b/2;a<=c*g||f<=c*g;)b/=2,g=b/2;for(var a=(a-c)/(g-1),f=(f-c)/(g-1),h=0;h<g;h++)e.push({x:Math.floor(a*h),y:Math.floor(f*h)},{x:Math.floor(a*h),y:Math.floor(f*(g-1-h))});return e};a.prototype.CHECK_INTERVAL=70;a.prototype.TRIGGER_VIEW_TIME=1E3;a.prototype.GRID_SIZE=64;a.prototype.VIEWABILITY_METHODS={INTERSECTION:"Intersection Observer",MOZ_INNER_SCREEN:"mozInnerScreen",REQUEST_ANIMATION_FRAME:"Request animation frame",ELEMENT_FROM_POINT:"Element from point"};a.prototype.helpers=
new d;a.prototype.getCheckingMethod=function(){if(window.IntersectionObserver)return this.VIEWABILITY_METHODS.INTERSECTION;if(window.mozInnerScreenY&&window.mozInnerScreenX)return this.VIEWABILITY_METHODS.MOZ_INNER_SCREEN;if(this.helpers.isIE())return this.VIEWABILITY_METHODS.ELEMENT_FROM_POINT;if(window.requestAnimationFrame)return this.VIEWABILITY_METHODS.REQUEST_ANIMATION_FRAME};a.prototype.initChecker=function(){switch(this.getCheckingMethod()){case this.VIEWABILITY_METHODS.INTERSECTION:this.initIntersectionChecker();
break;case this.VIEWABILITY_METHODS.MOZ_INNER_SCREEN:this.initMozChecker();break;case this.VIEWABILITY_METHODS.ELEMENT_FROM_POINT:this.initIEChecker();break;case this.VIEWABILITY_METHODS.REQUEST_ANIMATION_FRAME:this.initRequestAnimationFrameChecker()}};a.prototype.startTimer=function(b){this.timer=setTimeout(function(){"function"===typeof b&&b()}.bind(this),this.TRIGGER_VIEW_TIME)};a.prototype.resetTimer=function(){clearTimeout(this.timer);this.timer=null};a.prototype.initIntersectionChecker=function(){var b=
new window.IntersectionObserver(function(c){(c=.5<=c[0].intersectionRatio)&&!this.timer?this.startTimer(function(){this.triggerView();b.disconnect()}.bind(this)):c||this.viewed||this.resetTimer()}.bind(this),{threshold:.5});b.observe(document.body)};a.prototype.initRequestAnimationFrameChecker=function(){function b(){this.triggerView();document.body.removeChild(g)}function c(c,a){f[c].isVisible=a;for(var e=0,d=0;d<f.length;d++)f[d].isVisible&&e++;2<=e&&!this.timer&&!this.viewed&&this.startTimer(b.bind(this));
2>e&&this.timer&&this.resetTimer()}function a(c,b){var e=document.createElement("iframe");e.src="about:blank";e.width=b;e.height=b;e.frameBorder=0;e.style.cssText="left: "+(c.x-b/2)+"px; top: "+(c.y-b/2)+"px; position: absolute; border-style: none; display: block; pointer-events: none;";return e}var k=this.helpers.isSafari()?8:1,f=[{name:"top",left:"50%",top:"20%",isVisible:!1},{name:"bottom",left:"50%",top:"80%",isVisible:!1},{name:"left",left:"20%",top:"50%",isVisible:!1},{name:"right",left:"80%",
top:"50%",isVisible:!1}],g=document.createElement("div");g.style.cssText="left: 0px; top: 0px; width: 0px; height: 0px; position: absolute; z-index: -9999;";document.body.appendChild(g);for(var h=0;h<f.length;h++){var d=this.helpers.getPointCoordinatesByPercent(f[h].left,f[h].top),d=a(d,k);g.appendChild(d);d.contentWindow.onSetVisibility=c.bind(this);d.contentWindow.document.write("<script>("+this.initViewabilityIframeFn.toString()+")("+h+");\x3c/script>")}};a.prototype.initMozChecker=function(){this.initInterval(function(){var b=
window.screenY+window.outerHeight,b=window.screenY+55<window.mozInnerScreenY+window.innerHeight/2&&window.mozInnerScreenY+window.innerHeight/2<b,c=window.screenX,a=c+window.outerWidth;return c<window.mozInnerScreenX+window.innerWidth/2&&window.mozInnerScreenX+window.innerWidth/2<a&&b})};a.prototype.initIEChecker=function(){var b=this.helpers.getPointCoordinatesByPercent("50%","50%"),c=this.helpers.getGridPoints(this.GRID_SIZE,1);this.initInterval(function(){if(!document.elementFromPoint(b.x,b.y))return!1;
for(var a=0,d=0;d<c.length;d++){var f=c[d];document.elementFromPoint(f.x,f.y)&&a++}return a>=c.length/2})};a.prototype.initInterval=function(b){var c=setInterval(function(){var a=b();a&&!this.timer?this.startTimer(function(){this.triggerView();clearInterval(c)}.bind(this)):a||this.viewed||this.resetTimer()}.bind(this),this.CHECK_INTERVAL)};a.prototype.initViewabilityIframeFn=function(b){function a(c){window.onSetVisibility(b,c)}var d=null,k=function(){d&&clearTimeout(d);d=window.setTimeout(a.bind(null,
!1),100);a(!0);window.requestAnimationFrame(k)};window.requestAnimationFrame(k)};a.prototype.triggerView=function(){this.viewed=!0;this.helpers.createCallbackPixel(this.callbackUrl)};new a(window.__rtgViewability.url)})();
//@ sourceMappingURL=viewability.js.map